### ISSUE TITLE
Failed to start NameNode: Invalid URI for NameNode address (check fs.defaultFS): file:/// has no authority

### ISSUE THREAD

**Issue by momoking** [GELOG/docker-ubuntu-hadoop#19]
Hi, I was not able to start the NameNode:

```
2015-09-18 11:13:17,844 INFO  [main] namenode.NameNode (NameNode.java:setClientNamenodeAddress(349)) - fs.defaultFS is file:///
2015-09-18 11:13:18,084 WARN  [main] util.NativeCodeLoader (NativeCodeLoader.java:<clinit>(62)) - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2015-09-18 11:13:18,345 FATAL [main] namenode.NameNode (NameNode.java:main(1509)) - Failed to start namenode.
java.lang.IllegalArgumentException: Invalid URI for NameNode address (check fs.defaultFS): file:/// has no authority.
    at org.apache.hadoop.hdfs.server.namenode.NameNode.getAddress(NameNode.java:423)
    at org.apache.hadoop.hdfs.server.namenode.NameNode.getAddress(NameNode.java:413)
    at org.apache.hadoop.hdfs.server.namenode.NameNode.getRpcServerAddress(NameNode.java:464)
    at org.apache.hadoop.hdfs.server.namenode.NameNode.loginAsNameNodeUser(NameNode.java:564)
    at org.apache.hadoop.hdfs.server.namenode.NameNode.initialize(NameNode.java:584)
    at org.apache.hadoop.hdfs.server.namenode.NameNode.<init>(NameNode.java:762)
    at org.apache.hadoop.hdfs.server.namenode.NameNode.<init>(NameNode.java:746)
    at org.apache.hadoop.hdfs.server.namenode.NameNode.createNameNode(NameNode.java:1438)
    at org.apache.hadoop.hdfs.server.namenode.NameNode.main(NameNode.java:1504)
2015-09-18 11:13:18,358 INFO  [main] util.ExitUtil (ExitUtil.java:terminate(124)) - Exiting with status 1
2015-09-18 11:13:18,359 INFO  [Thread-1] namenode.NameNode (StringUtils.java:run(659)) - SHUTDOWN_MSG: 
/************************************************************
SHUTDOWN_MSG: Shutting down NameNode at hdfs-namenode/172.17.0.28
************************************************************/
```

Here is what I have done:

```
docker build /path_to_my_clone/docker-ubuntu-hadoop/2.6.0
```

```
mkdir -p ~/data/hadoop/hdfs
```

formatting:

```
docker run --rm -i -h hdfs-namenode \
    -v $HOME/data/hadoop/hdfs:/data \
    gelog/hadoop hdfs namenode -format
```

starting NN:

```
docker run -d --name hdfs-namenode \
    -h hdfs-namenode -p 50070:50070 \
    -v $HOME/data/hadoop/hdfs:/data \
    gelog/hadoop hdfs namenode && \
docker logs -f hdfs-namenode
```

Could it be ...
- It doesn't point to the right core-site.xml? 
- missing fs.defaultFS in config?
- I need to have a special user 'hdfs' to start NN?

**Comment by davidonlaptop** [comment]
1) Yes, something is wrong with your paths. Start by investigating your run command because you're not using the image you've just built.

2) Missing `fs.defaultFS`.. I don't know, have you configured this variable locally?

3) Not required, but that could be an improvement this image.

**Comment by momoking** [comment]
I started over again. This time, I ran the image and go inside with /bin/bash:

`echo $HADOOP_INSTALL` points to `/usr/local/hadoop/`  (which is correct)

`echo $HADOOP_CONF_DIR` points to `/data/conf` (According to the DockerFile, it is suppose to be `/usr/local/hadoop/etc/hadoop`, right?)

`vi /usr/local/hadoop/etc/hadoop/core-site.xml` contains no configuration
`vi /usr/local/hadoop/etc/hadoop/hdfs-site.xml` contains no configuration

`/data` exists but empty. `/data/conf` does not exits

**Comment by davidonlaptop** [comment]
You're not running the correct Docker image; e.g. you have an error in your docker run command.

Do: `docker run --help` and compare with your `docker run command`:
1. What's the image name you're running?
2. What's the image name that you've built locally?

**Comment by momoking** [comment]
After building the images:

```
box:hdfs momoking$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
<none>              <none>              29d442973d61        5 minutes ago       862.4 MB
ubuntu              14.04               91e54dfb1179        4 weeks ago         188.4 MB
```

I'm guessing `29d442973d61` is the image I just built. Then I run the image by its id:

`docker run -t -i --name hdfs-namenode -h hdfs-namenode -p 50070:50070 -v $HOME/data/hadoop/hdfs:/data 29d442973d61 /bin/bash`

```
root@hdfs-namenode:/# echo $HADOOP_VERSION 
2.6.0
root@hdfs-namenode:/# echo $HADOOP_HOME/   
/usr/local/hadoop/
root@hdfs-namenode:/# echo $HADOOP_CONF_DIR
```

**Comment by davidonlaptop** [comment]
Yes, now you're using the image you've built. Is your problem solved?

BTW you can give a meaningful name to your image using the `docker build -t`.

**Comment by momoking** [comment]
The problem persist. I suspect that hadoop is not build correctly to use the correct *.xml configuration. Since `echo $HADOOP_CONF_DIR` returns the wrong path. Let's talk about this during class. ;)

**Comment by mikefaille** [comment]
@momoking This hadoop build is an official one. It would be surprising if you found crittical bug like this. Maybe, the current path is not the right one. I don't have time right know to fix it. Maybe, if you find something, you must point clues here and in your report (a suggestion ;-) ).
If you want to be sure where hadoop take is config, start hadoop using verbose or debug logs (as you wish).

**Comment by momoking** [comment]
I think the issue is because of `docker run -v` that doesn't mount the volume correctly for Mac. Therefore hdfs couldn't find the correct xml config file.

I ran the exact same commands on school's server and it works like a charm.

Thank you for the support

**Comment by mikefaille** [comment]
@momoking  You're welcome. :-) You can add this note on your report.

**Comment by davidonlaptop** [comment]
Ah!  It could be because your volume is not in your home directory.
Boot2Docker mounts $HOME by default into the boot2docker VM and you must
use an absolute path without symbolic link or it won't work.

**Comment by codingtony** [comment]
+1 for data only container pattern :-) 

It works with boot2docker without modification

**Comment by momoking** [comment]
OK it works on my laptop now ;-) Thanks.

For Mac: use `/Users/yourname/` instead of `$HOME`

@davidonlaptop @mikefaille J'ai fait un pull-request d'une version modifier de README a propos de ce issue.

**Comment by davidonlaptop** [comment]
Which osx version you have?

$HOME works on OSX 10.10

**Comment by momoking** [comment]
I have 10.10 as well. I just tried once more with $HOME and it works this time. It is weird.

**Comment by davidonlaptop** [comment]
Maybe you had been using '~/' instead of '$HOME'. The former does not work
- not sure why.

**Comment by davidonlaptop** [comment]
potentially because $HOME gets replaced by the shell before the command is
sent to docker.

**Comment by davidonlaptop** [comment]
Won't fix.
