### ISSUE TITLE
Dockerfile - Cleanup environment variables

### ISSUE THREAD

**Issue by davidonlaptop** [GELOG/docker-ubuntu-hadoop#2]
Remove all non required environment variables. There should be only two variables:
- `HADOOP_VERSION`
- `HADOOP_HOME`

For example, see our hbase image:
https://github.com/GELOG/docker-ubuntu-hbase/blob/001b7e74d7a10d9d77d1f7b1ca1ba0b029a86c2b/Dockerfile

**Comment by codingtony** [comment]
How you want the versions specified? 

e.g : 

```
ENV WGET_VERSION       1.15-1ubuntu1.14.04.1
...
apt-get install -y wget=$WGET_VERSION
```

IMO There should be 3 variables (since PATH is also defined in the HBase Dockerfile)

**Comment by davidonlaptop** [comment]
Correct, PATH needs to be present as well.

As for WGET, I am not sure what is the best course of actions. Since we don't need wget in the image, it is just a mean to download the file.  I'd like to get rid of WGET if that is possible at all.

I tried (with an older version of Docker) to download the file with an ADD instruction and a dockerignore instructions to tell it not to store the file in a layer, but it didn't work for me. Perhaps it is fixed in Docker 1.8.

**Comment by codingtony** [comment]
Anyway do we really care about wget version? 
Isn't  apt-get install -y wget enough?

**Comment by codingtony** [comment]
If you really want wget out of the image, what about merging : 

```
RUN \
    apt-get update && \
    apt-get install -y wget && \
    rm -rf /var/lib/apt/lists/*
```

With the "Installing Hadoop step" , then remove wget within the same step ?

**Comment by codingtony** [comment]
I think we should also leave ENV JAVA_HOME in the image.

**Comment by codingtony** [comment]
There's a good reason for that :

```
docker run --rm -i -h hdfs-namenode   -v $HOME/data/hadoop/hdfs:/data     gelog/hadoop hdfs namenode -format

Error: JAVA_HOME is not set and could not be found.
```

**Comment by davidonlaptop** [comment]
+1 for merging the wget install step with the Hadoop install step

Yes, we should kept both JAVA_HOME and JAVA_VERSION as well.

**Comment by codingtony** [comment]
Almost done with the PR... however I removed JAVA_VERSION. the version is
specified in  the RUN apt-get line.

**Comment by davidonlaptop** [comment]
Fixed by @codingtony and merged into master branch.
