### ISSUE TITLE
push new 2.6.0 docker image to docker hub

### ISSUE THREAD

**Issue by jar349** [GELOG/docker-ubuntu-hadoop#32]
I keep running into the issue described in #30 .  I finally just ran bash against gelog/hadoop:2.6.0 and discovered that the only sudirectory in /data is ./conf.  I did some investigation and realized that even though you merged the fix, the fix doesn't exist in the version pushed to docker hub.

Please re-build 2.6.0 and re-push it to docker hub?

**Comment by davidonlaptop** [comment]
Hi @jar349 . Thanks for reporting this bug. We'll try to fix this tonight.

**Comment by davidonlaptop** [comment]
The URL of the repo has changed since the image has been configured on the Docker Hub, and I don't see how I can change it in the Docker Hub...

I've triggered a new build of the default image. Hopefully it will pickup the redirect provided by GitHub.

**Comment by jar349** [comment]
it looks like the :latest tag was updated an hour ago.  :2.6.0 is still from a year ago, however.

**Comment by davidonlaptop** [comment]
The image with "latest" tag is pulling from the master branch, so it should have the 2.6.0 code with the patch.

You're right, we should update the "2.6.0" tagged version as well. But would you be so kind to give it a try and tell me if the problem is solved with "latest" first ?

**Comment by jar349** [comment]
yup, running.

Edit: I suppose I should be more clear.  Yes, it runs correctly now.  Thank you.

**Comment by davidonlaptop** [comment]
Thanks :-p

**Comment by davidonlaptop** [comment]
FYI. An image is now building with tag named "2.6.0-ec2".
